// Edit all page text here.
// align: 'l' = text left, 'r' = text right, 'c' = centered
// shape/cx/scale control the particle animation (unchanged)
export const SCHOOL = 'Chakhari Prathomik Vidyaloy'

export const NAV = [
  { label: 'Home', to: 'hero' },
  { label: 'About', to: 'about' },
  { label: 'Academics', to: 'academics' },
  { label: 'Contact', to: 'admission' },
]

export const SECTIONS = [
  { id: 'hero', shape: 'brain', cx: 0.42, scale: 0.34, align: 'l', hero: true,
    eyebrow: 'Learn. Grow. Shine.', title: 'Building bright futures.',
    text: 'A joyful place where every child learns, explores and grows with confidence.',
    button: { label: 'Discover our school', to: 'about' } },
  { id: 'about', shape: 'brain', cx: -0.4, scale: 0.5, align: 'r',
    eyebrow: 'A place to learn', title: 'Every child has potential.',
    text: 'At Chakhari Prathomik Vidyaloy, we provide a caring and supportive environment where children can learn with curiosity, confidence and happiness.' },
  { id: 'learning', shape: 'scatter', cx: 0, scale: 0.4, align: 'c',
    eyebrow: 'Joyful education', title: 'Learning should be joyful.',
    text: 'We make learning simple, engaging and meaningful through classroom lessons, activities and regular guidance from our teachers.' },
  { id: 'education', shape: 'bulb', cx: -0.38, scale: 0.5, align: 'r',
    eyebrow: 'Strong foundations', title: 'Education beyond books.',
    text: 'Along with academics, we encourage creativity, discipline, communication, teamwork and respect.' },
  { id: 'approach', shape: 'globe', cx: 0.35, scale: 0.4, align: 'l',
    eyebrow: 'Our approach', title: 'Growing curious minds.',
    text: 'We encourage every student to think, ask questions, explore new ideas and enjoy the process of learning.' },
  { id: 'students', shape: 'scatter', cx: 0, scale: 0.4, align: 'c',
    eyebrow: 'Every student matters', title: 'Learning with confidence.',
    text: 'Every child receives care, encouragement and equal opportunities to participate, learn and grow.' },
  { id: 'teachers', shape: 'brain', cx: 0.4, scale: 0.45, align: 'l',
    eyebrow: 'Our teachers', title: 'Guidance that inspires.',
    text: 'Our teachers guide students with patience and care while building knowledge, confidence and positive values.' },
  { id: 'together', shape: 'globe', cx: -0.35, scale: 0.4, align: 'r',
    eyebrow: 'Learning together', title: 'Friendship. Teamwork. Respect.',
    text: 'School helps children learn how to communicate, cooperate, share and respect one another.' },
  { id: 'vision', shape: 'bulb', cx: 0.36, scale: 0.5, align: 'l',
    eyebrow: 'Our vision', title: 'A brighter future begins here.',
    text: 'We aim to build a strong educational foundation that helps every child move forward with knowledge and confidence.' },
  { id: 'mission', shape: 'brain', cx: -0.4, scale: 0.5, align: 'r',
    eyebrow: 'Our mission', title: 'Learning with purpose.',
    text: 'Our mission is to make primary education meaningful, enjoyable and accessible to every student.' },
  { id: 'academics', shape: 'scatter', cx: 0, scale: 0.4, align: 'c',
    eyebrow: 'Primary education', title: 'A strong start to learning.',
    text: 'We focus on developing essential academic skills and helping children understand concepts with clarity.' },
  { id: 'activities', shape: 'swirl', cx: 0.35, scale: 0.32, align: 'l',
    eyebrow: 'Beyond the classroom', title: 'Learning through experiences.',
    text: 'Creative activities, games, storytelling and cultural programmes make the learning journey more enjoyable.' },
  { id: 'parents', shape: 'globe', cx: -0.35, scale: 0.4, align: 'r',
    eyebrow: 'School & family', title: 'Together for every child.',
    text: 'We believe teachers and parents working together can create a stronger learning experience for every child.' },
  { id: 'admission', shape: 'scatter', cx: 0, scale: 0.4, align: 'c',
    eyebrow: 'Admissions', title: 'Begin the learning journey.',
    text: 'Contact Chakhari Prathomik Vidyaloy for admission information, school timings and other details.',
    button: { label: 'Contact school', to: 'admission' } },
  { id: 'final', shape: 'swirl', cx: 0, scale: 0.32, align: 'c',
    title: 'Small steps today.\nBright futures tomorrow.',
    text: 'Every school day is a new opportunity to learn, discover and grow.',
    button: { label: 'Welcome to our school', to: 'hero' } },
]
